### ISSUE TITLE
Create new match: randomize

### ISSUE THREAD

**Issue by citizenblr** [Wenomer/kicker-generator#11]
Rough mockup attached

![randomize match](https://cloud.githubusercontent.com/assets/850334/8303667/15956d3a-19a8-11e5-91dc-7f804d958b13.png)

**Comment by alex-s** [comment]
@citizenblr maybe we can use http://kicker.indevelopment.us/tournament for that?

**Comment by Wenomer** [comment]
@citizenblr will be use generation page
